# Generated by Django 5.2.1 on 2025-07-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_publicacion_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('BOR', 'Borrador'), ('PEN', 'Pendiente de Revisión'), ('PUB', 'Publicado')], default='BOR', max_length=3),
        ),
    ]
